-- MySQL Script generated by MySQL Workbench
-- Sat Oct 10 19:02:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Client` ;

CREATE TABLE IF NOT EXISTS `Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `idGoogleLogin` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Seller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Seller` ;

CREATE TABLE IF NOT EXISTS `Seller` (
  `idSeller` INT NOT NULL AUTO_INCREMENT,
  `loginName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSeller`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Shop` ;

CREATE TABLE IF NOT EXISTS `Shop` (
  `idShop` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `maxCapacity` INT NOT NULL,
  `type` TINYINT(1) NOT NULL,
  `seller` INT NOT NULL,
  PRIMARY KEY (`idShop`),
  CONSTRAINT `fk_Shop_Seller1`
    FOREIGN KEY (`seller`)
    REFERENCES `Seller` (`idSeller`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Shop_Seller1_idx` ON `Shop` (`seller` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Reservation` ;

CREATE TABLE IF NOT EXISTS `Reservation` (
  `idReservation` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `state` TINYINT(1) NOT NULL,
  `remarks` VARCHAR(45) NULL,
  `client` INT NOT NULL,
  `shop` INT NOT NULL,
  PRIMARY KEY (`idReservation`),
  CONSTRAINT `fk_table1_Client`
    FOREIGN KEY (`client`)
    REFERENCES `Client` (`idClient`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Shop1`
    FOREIGN KEY (`shop`)
    REFERENCES `Shop` (`idShop`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_table1_Client_idx` ON `Reservation` (`client` ASC) VISIBLE;

CREATE INDEX `fk_Reservation_Shop1_idx` ON `Reservation` (`shop` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ControlParameter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ControlParameter` ;

CREATE TABLE IF NOT EXISTS `ControlParameter` (
  `idControlParameter` INT NOT NULL AUTO_INCREMENT,
  `shop` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idControlParameter`),
  CONSTRAINT `fk_ControlParameter_Shop1`
    FOREIGN KEY (`shop`)
    REFERENCES `Shop` (`idShop`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_ControlParameter_Shop1_idx` ON `ControlParameter` (`shop` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
